# -*- coding: utf-8 -*-
"""Copie de Copie de Streamlit - ADHD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ighAFwLxRZ2Kb2-yBysujtonhRbzL4Od
"""
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# Machine Learning
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report, roc_curve
from sklearn.feature_selection import SelectKBest, f_classif, RFE
from sklearn.impute import SimpleImputer

import joblib
import requests
from io import BytesIO
import warnings
import os
import time
from datetime import datetime

warnings.filterwarnings('ignore')

# Configuration de la page
st.set_page_config(
    page_title="Dépistage TDAH - IA Avancée",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

if 'asrs_responses' not in st.session_state:
    st.session_state.asrs_responses = {}

if 'last_topic' not in st.session_state:
    st.session_state.last_topic = 'X'

if 'run' not in st.session_state:
    st.session_state.run = False

# Style CSS amélioré
st.markdown("""
<style>
    .main-header {
        font-size: 2.8rem;
        color: #1a237e;
        text-align: center;
        margin-bottom: 2rem;
        font-weight: bold;
    }
    .sub-header {
        font-size: 1.8rem;
        color: #3949ab;
        margin-bottom: 1rem;
    }
    .metric-card {
        background: linear-gradient(145deg, #e3f2fd, #bbdefb);
        border-radius: 15px;
        padding: 1.5rem;
        margin: 0.5rem 0;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        border-left: 5px solid #1976d2;
    }
    .warning-box {
        background: linear-gradient(145deg, #fff3e0, #ffe0b2);
        border: 2px solid #ff9800;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
    }
    .success-box {
        background: linear-gradient(145deg, #e8f5e8, #c8e6c8);
        border: 2px solid #4caf50;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
    }
    .info-box {
        background: linear-gradient(145deg, #e3f2fd, #bbdefb);
        border: 2px solid #2196f3;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
    }
    .stProgress > div > div > div > div {
        background-color: #1976d2;
    }
</style>
""", unsafe_allow_html=True)

# =================== FONCTIONS DE CHARGEMENT ET PREPROCESSING ===================

@st.cache_data(ttl=3600, show_spinner="Chargement des données...")
def load_data(file_id=None, local_file=None):
    """Charge le dataset TDAH avec gestion d'erreur robuste"""
    try:
        # Tentative de chargement depuis Google Drive
        if file_id is not None:
            try:
                url = f'https://drive.google.com/uc?export=download&id={file_id}'
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                
                # Essayer différentes options de parsing
                for encoding in ['utf-8', 'latin-1', 'ISO-8859-1']:
                    for sep in [',', ';', '\t']:
                        try:
                            df = pd.read_csv(BytesIO(response.content), encoding=encoding, sep=sep)
                            if not df.empty and len(df.columns) > 1:
                                return df
                        except Exception:
                            continue
            except Exception as e:
                st.warning(f"⚠️ Erreur de chargement depuis Drive: {str(e)}")
        
        # Tentative de chargement depuis un fichier local
        if local_file is not None:
            try:
                for encoding in ['utf-8', 'latin-1', 'ISO-8859-1']:
                    for sep in [',', ';', '\t']:
                        try:
                            df = pd.read_csv(local_file, encoding=encoding, sep=sep)
                            if not df.empty and len(df.columns) > 1:
                                return df
                        except Exception:
                            continue
            except Exception as e:
                st.warning(f"⚠️ Erreur de chargement du fichier local: {str(e)}")
        
        # Upload de fichier par l'utilisateur
        uploaded_file = st.file_uploader("Choisir un fichier CSV", type="csv")
        if uploaded_file is not None:
            try:
                for encoding in ['utf-8', 'latin-1', 'ISO-8859-1']:
                    for sep in [',', ';', '\t']:
                        try:
                            df = pd.read_csv(uploaded_file, encoding=encoding, sep=sep)
                            if not df.empty and len(df.columns) > 1:
                                return df
                        except Exception:
                            continue
            except Exception as e:
                st.warning(f"⚠️ Erreur de chargement du fichier uploadé: {str(e)}")
        
        # Si tout échoue, créer un jeu de données de démonstration
        st.warning("⚠️ Utilisation d'un jeu de données de démonstration")
        return create_demo_dataset()
    
    except Exception as e:
        st.error(f"❌ Erreur critique: {str(e)}")
        return create_demo_dataset()
        
def create_demo_dataset():
    """Crée un jeu de données de démonstration pour le TDAH"""
    np.random.seed(42)
    n = 100
    
    # Créer des données aléatoires mais cohérentes
    data = {
        'Age': np.random.randint(10, 65, n),
        'Genre': np.random.choice(['Homme', 'Femme'], n),
        'Inattention_Score': np.random.uniform(1, 10, n),
        'Hyperactivite_Score': np.random.uniform(1, 10, n),
        'Impulsivite_Score': np.random.uniform(1, 10, n),
        'TDAH': np.random.choice(['Oui', 'Non'], n, p=[0.3, 0.7])
    }
    
    df = pd.DataFrame(data)
    st.info("ℹ️ Données de démonstration chargées")
    return df


@st.cache_data
def advanced_preprocessing(df, target_column='TDAH'):
    """Préprocessing avancé avec feature engineering"""
    if df is None or df.empty:
        return None, None

    df_processed = df.copy()

    # 1. Gestion des valeurs manquantes
    numeric_cols = df_processed.select_dtypes(include=[np.number]).columns
    categorical_cols = df_processed.select_dtypes(include=['object']).columns

    # Imputation numérique
    for col in numeric_cols:
        if df_processed[col].isnull().sum() > 0:
            df_processed[col].fillna(df_processed[col].median(), inplace=True)

    # Imputation catégorielle
    for col in categorical_cols:
        if col != target_column and df_processed[col].isnull().sum() > 0:
            df_processed[col].fillna(df_processed[col].mode()[0], inplace=True)

    # 2. Feature Engineering
    feature_info = {}

    # Création de nouvelles features si les colonnes scores existent
    score_columns = [col for col in df_processed.columns if 'score' in col.lower()]
    if len(score_columns) >= 2:
        df_processed['Score_Total'] = df_processed[score_columns].sum(axis=1)
        df_processed['Score_Moyen'] = df_processed[score_columns].mean(axis=1)
        feature_info['engineered_features'] = ['Score_Total', 'Score_Moyen']

    # Binning de l'âge si disponible
    if 'Age' in df_processed.columns:
        df_processed['Age_Group'] = pd.cut(df_processed['Age'],
                                         bins=[0, 12, 18, 30, 50, 100],
                                         labels=['Enfant', 'Adolescent', 'Jeune_Adulte', 'Adulte', 'Senior'])
        feature_info['age_groups'] = True

    # 3. Encodage des variables catégorielles
    categorical_mappings = {}
    for col in categorical_cols:
        if col != target_column:
            le = LabelEncoder()
            df_processed[f'{col}_encoded'] = le.fit_transform(df_processed[col])
            categorical_mappings[col] = le

    feature_info['categorical_mappings'] = categorical_mappings
    feature_info['original_shape'] = df.shape
    feature_info['processed_shape'] = df_processed.shape

    return df_processed, feature_info

# =================== FONCTIONS MACHINE LEARNING AVANCÉES ===================

@st.cache_resource
def train_multiple_models(df, target_column='TDAH'):
    """Entraîne plusieurs modèles ML avec optimisation d'hyperparamètres"""
    try:
        if df is None or target_column not in df.columns:
            return None, None, None, None

        # Préparation des données
        X = df.drop(columns=[target_column])
        y = df[target_column].map({'Oui': 1, 'Non': 0})

        # Supprimer les lignes avec des valeurs cibles manquantes
        mask = y.notna()
        X = X[mask]
        y = y[mask]

        if len(X) < 10:
            st.error("❌ Pas assez de données pour l'entraînement")
            return None, None, None, None

        # Sélection des features numériques
        numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()

        if len(numeric_features) == 0:
            st.error("❌ Aucune feature numérique trouvée")
            return None, None, None, None

        X_numeric = X[numeric_features]

        # Division train/test
        X_train, X_test, y_train, y_test = train_test_split(
            X_numeric, y, test_size=0.2, random_state=42, stratify=y
        )

        # Standardisation
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # Définition des modèles et hyperparamètres
        models_params = {
            'Random Forest': {
                'model': RandomForestClassifier(random_state=42),
                'params': {
                    'n_estimators': [50, 100, 200],
                    'max_depth': [5, 10, None],
                    'min_samples_split': [2, 5, 10]
                }
            },
            'Logistic Regression': {
                'model': LogisticRegression(random_state=42, max_iter=1000),
                'params': {
                    'C': [0.1, 1.0, 10.0],
                    'penalty': ['l1', 'l2'],
                    'solver': ['liblinear']
                }
            },
            'SVM': {
                'model': SVC(random_state=42, probability=True),
                'params': {
                    'C': [0.1, 1.0, 10.0],
                    'kernel': ['rbf', 'linear'],
                    'gamma': ['scale', 'auto']
                }
            },
            'Gradient Boosting': {
                'model': GradientBoostingClassifier(random_state=42),
                'params': {
                    'n_estimators': [50, 100],
                    'learning_rate': [0.1, 0.2],
                    'max_depth': [3, 5]
                }
            }
        }

        # Entraînement et optimisation
        results = {}
        best_models = {}

        for name, config in models_params.items():
            with st.spinner(f"Optimisation {name}..."):
                grid_search = GridSearchCV(
                    config['model'],
                    config['params'],
                    cv=3,
                    scoring='roc_auc',
                    n_jobs=-1
                )

                if name in ['Logistic Regression', 'SVM']:
                    grid_search.fit(X_train_scaled, y_train)
                    y_pred = grid_search.predict(X_test_scaled)
                    y_pred_proba = grid_search.predict_proba(X_test_scaled)[:, 1]
                else:
                    grid_search.fit(X_train, y_train)
                    y_pred = grid_search.predict(X_test)
                    y_pred_proba = grid_search.predict_proba(X_test)[:, 1]

                # Métriques
                accuracy = accuracy_score(y_test, y_pred)
                auc_score = roc_auc_score(y_test, y_pred_proba)

                results[name] = {
                    'accuracy': accuracy,
                    'auc_score': auc_score,
                    'best_params': grid_search.best_params_,
                    'best_score': grid_search.best_score_,
                    'y_pred': y_pred,
                    'y_pred_proba': y_pred_proba
                }

                best_models[name] = grid_search.best_estimator_

        return results, best_models, scaler, (X_test, y_test)

    except Exception as e:
        st.error(f"❌ Erreur ML : {str(e)}")
        return None, None, None, None

def perform_feature_analysis(df, target_column='TDAH'):
    """Analyse des features avec sélection automatique"""
    if df is None or target_column not in df.columns:
        return None

    X = df.select_dtypes(include=[np.number]).drop(columns=[target_column], errors='ignore')
    y = df[target_column].map({'Oui': 1, 'Non': 0})

    # Supprimer les valeurs manquantes
    mask = y.notna()
    X = X[mask]
    y = y[mask]

    if len(X) == 0:
        return None

    # Sélection des meilleures features
    selector = SelectKBest(score_func=f_classif, k=min(10, len(X.columns)))
    X_selected = selector.fit_transform(X, y)

    # Scores des features
    feature_scores = pd.DataFrame({
        'Feature': X.columns,
        'Score': selector.scores_,
        'P_value': selector.pvalues_
    }).sort_values('Score', ascending=False)

    return feature_scores

# =================== PAGES DE L'APPLICATION ===================

def page_accueil():
    """Page d'accueil avec présentation du projet"""
    st.markdown('<h1 class="main-header">🧠 Dépistage TDAH - IA Avancée</h1>', unsafe_allow_html=True)

    # Avertissement médical
    st.markdown("""
    <div class="warning-box">
    <h4>⚠️ Avertissement Médical Important</h4>
    <p>Cet outil utilise l'intelligence artificielle pour le dépistage du TDAH à des fins de recherche et d'information uniquement.
    Il ne remplace en aucun cas un diagnostic médical professionnel.
    Consultez toujours un professionnel de santé qualifié pour un diagnostic définitif.</p>
    </div>
    """, unsafe_allow_html=True)

    # Chargement des données pour les statistiques
    df = load_data()

    # Statistiques principales
    col1, col2, col3, col4 = st.columns(4)

    if df is not None:
        with col1:
            st.markdown(f"""
            <div class="metric-card">
            <h3 style="color: #1976d2;">{len(df)}</h3>
            <p>Échantillons dans les données</p>
            </div>
            """, unsafe_allow_html=True)

        with col2:
            if 'TDAH' in df.columns:
                tdah_count = (df['TDAH'] == 'Oui').sum()
                st.markdown(f"""
                <div class="metric-card">
                <h3 style="color: #1976d2;">{tdah_count}</h3>
                <p>Cas TDAH détectés</p>
                </div>
                """, unsafe_allow_html=True)
            else:
                st.markdown("""
                <div class="metric-card">
                <h3 style="color: #1976d2;">5-7%</h3>
                <p>Prévalence mondiale</p>
                </div>
                """, unsafe_allow_html=True)

        with col3:
            st.markdown(f"""
            <div class="metric-card">
            <h3 style="color: #1976d2;">{len(df.columns)}</h3>
            <p>Variables analysées</p>
            </div>
            """, unsafe_allow_html=True)

        with col4:
            st.markdown("""
            <div class="metric-card">
            <h3 style="color: #1976d2;">4</h3>
            <p>Algorithmes ML</p>
            </div>
            """, unsafe_allow_html=True)
    else:
        # Statistiques par défaut si pas de données
        stats = [
            ("5-7%", "Prévalence mondiale"),
            ("3:1", "Ratio H/F"),
            ("18", "Questions ASRS"),
            ("95%", "Précision IA")
        ]

        for i, (value, label) in enumerate(stats):
            with [col1, col2, col3, col4][i]:
                st.markdown(f"""
                <div class="metric-card">
                <h3 style="color: #1976d2;">{value}</h3>
                <p>{label}</p>
                </div>
                """, unsafe_allow_html=True)

    # Description du TDAH
    st.markdown('<h2 class="sub-header">📖 Comprendre le TDAH</h2>', unsafe_allow_html=True)

    col1, col2 = st.columns([2, 1])

    with col1:
        st.markdown("""
        <div class="info-box">
        <p>Le <strong>Trouble du Déficit de l'Attention avec ou sans Hyperactivité (TDAH)</strong>
        est un trouble neurodéveloppemental caractérisé par trois symptômes principaux :</p>

        <h4 style="color: #1976d2;">🎯 Inattention</h4>
        <ul>
        <li>Difficultés de concentration et d'attention soutenue</li>
        <li>Erreurs d'inattention dans les tâches</li>
        <li>Problèmes d'organisation et de planification</li>
        <li>Évitement des tâches nécessitant un effort mental</li>
        </ul>

        <h4 style="color: #1976d2;">⚡ Hyperactivité</h4>
        <ul>
        <li>Agitation motrice excessive</li>
        <li>Difficulté à rester assis ou calme</li>
        <li>Sensation d'être constamment "en mouvement"</li>
        <li>Bavardage excessif</li>
        </ul>

        <h4 style="color: #1976d2;">🚀 Impulsivité</h4>
        <ul>
        <li>Difficulté à attendre son tour</li>
        <li>Interruption fréquente des autres</li>
        <li>Prises de décision rapides sans réflexion</li>
        <li>Difficultés de self-contrôle</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        # Graphique en secteurs
        fig = px.pie(
            values=[33, 33, 34],
            names=['Inattention', 'Hyperactivité', 'Impulsivité'],
            title="Répartition des symptômes TDAH",
            color_discrete_sequence=['#1976d2', '#2196f3', '#64b5f6'],
            hole=0.4
        )
        fig.update_layout(
            font_size=12,
            title_font_size=16,
            height=400
        )
        st.plotly_chart(fig, use_container_width=True)

    # Outils disponibles
    st.markdown('<h2 class="sub-header">🛠️ Outils d\'IA disponibles</h2>', unsafe_allow_html=True)

    tools_col1, tools_col2, tools_col3 = st.columns(3)

    with tools_col1:
        st.markdown("""
        <div class="metric-card">
        <h4 style="color: #1976d2;">📝 Test ASRS-v1.1</h4>
        <ul>
        <li>Questionnaire officiel de l'OMS</li>
        <li>18 questions validées scientifiquement</li>
        <li>Scoring automatique et interprétation</li>
        <li>Recommandations personnalisées</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

    with tools_col2:
        st.markdown("""
        <div class="metric-card">
        <h4 style="color: #1976d2;">🤖 IA Multi-Algorithmes</h4>
        <ul>
        <li>Random Forest optimisé</li>
        <li>SVM avec kernel RBF</li>
        <li>Régression Logistique</li>
        <li>Gradient Boosting</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

    with tools_col3:
        st.markdown("""
        <div class="metric-card">
        <h4 style="color: #1976d2;">📊 Analytics Avancés</h4>
        <ul>
        <li>Feature engineering automatique</li>
        <li>Grid Search d'hyperparamètres</li>
        <li>Sélection de features</li>
        <li>Validation croisée</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

def page_exploration():
    """Page d'exploration des données approfondie"""
    st.markdown('<h1 class="main-header">📊 Exploration Avancée des Données</h1>', unsafe_allow_html=True)

    # Chargement des données
    df = load_data()
    if df is None:
        st.error("❌ Impossible de charger les données")
        return

    # Preprocessing
    df_processed, feature_info = advanced_preprocessing(df)

    if df_processed is None:
        st.error("❌ Erreur lors du preprocessing")
        return

    # Onglets pour différentes analyses
    tab1, tab2, tab3, tab4 = st.tabs(["📈 Vue d'ensemble", "🔍 Analyse par variable", "🔗 Corrélations", "🎯 Feature Engineering"])

    with tab1:
        # Vue d'ensemble
        col1, col2, col3, col4, col5 = st.columns(5)

        with col1:
            st.metric("Lignes", len(df_processed))
        with col2:
            st.metric("Colonnes", len(df_processed.columns))
        with col3:
            missing_pct = (df_processed.isnull().sum().sum() / (df_processed.shape[0] * df_processed.shape[1])) * 100
            st.metric("Données manquantes", f"{missing_pct:.1f}%")
        with col4:
            if 'TDAH' in df_processed.columns:
                tdah_pct = (df_processed['TDAH'] == 'Oui').mean() * 100
                st.metric("% TDAH", f"{tdah_pct:.1f}%")
        with col5:
            numeric_cols = len(df_processed.select_dtypes(include=[np.number]).columns)
            st.metric("Variables numériques", numeric_cols)

        # Distribution de la variable cible
        if 'TDAH' in df_processed.columns:
            st.subheader("🎯 Distribution de la variable cible")

            col1, col2 = st.columns(2)

            with col1:
                tdah_counts = df_processed['TDAH'].value_counts()
                fig = px.pie(values=tdah_counts.values, names=tdah_counts.index,
                           title="Répartition TDAH vs Non-TDAH",
                           color_discrete_sequence=['#ff7f0e', '#1f77b4'])
                st.plotly_chart(fig, use_container_width=True)

            with col2:
                fig = px.bar(x=tdah_counts.index, y=tdah_counts.values,
                           title="Nombre de cas par catégorie",
                           color=tdah_counts.index,
                           color_discrete_sequence=['#1f77b4', '#ff7f0e'])
                st.plotly_chart(fig, use_container_width=True)

        # Statistiques descriptives
        st.subheader("📊 Statistiques descriptives")
        numeric_df = df_processed.select_dtypes(include=[np.number])
        st.dataframe(numeric_df.describe().round(2), use_container_width=True)

    with tab2:
        # Analyse par variable
        st.subheader("🔍 Analyse détaillée par variable")

        selected_var = st.selectbox("Choisir une variable à analyser", df_processed.columns)

        col1, col2 = st.columns(2)

        with col1:
            # Distribution de la variable
            if df_processed[selected_var].dtype == 'object':
                value_counts = df_processed[selected_var].value_counts()
                fig = px.bar(x=value_counts.index, y=value_counts.values,
                           title=f"Distribution de {selected_var}")
                if 'TDAH' in df_processed.columns:
                    fig = px.histogram(df_processed, x=selected_var, color='TDAH',
                                     title=f"Distribution de {selected_var} par groupe TDAH")
            else:
                fig = px.histogram(df_processed, x=selected_var, nbins=30,
                                 title=f"Distribution de {selected_var}")
                if 'TDAH' in df_processed.columns:
                    fig = px.histogram(df_processed, x=selected_var, color='TDAH',
                                     title=f"Distribution de {selected_var} par groupe TDAH",
                                     opacity=0.7)

            st.plotly_chart(fig, use_container_width=True)

        with col2:
            # Comparaison par groupe TDAH
            if df_processed[selected_var].dtype != 'object' and 'TDAH' in df_processed.columns:
                fig = px.box(df_processed, x='TDAH', y=selected_var, color='TDAH',
                           title=f"Comparaison {selected_var} par groupe TDAH")
                st.plotly_chart(fig, use_container_width=True)
            else:
                # Statistiques de la variable
                st.subheader("Statistiques")
                if df_processed[selected_var].dtype == 'object':
                    stats_df = df_processed[selected_var].value_counts().to_frame()
                    stats_df['Pourcentage'] = (stats_df[selected_var] / len(df_processed) * 100).round(2)
                    st.dataframe(stats_df, use_container_width=True)
                else:
                    stats = df_processed[selected_var].describe()
                    st.dataframe(stats.to_frame().T, use_container_width=True)

        # Tests statistiques si TDAH disponible
        if 'TDAH' in df_processed.columns and df_processed[selected_var].dtype != 'object':
            st.subheader("🧪 Test statistique")
            from scipy import stats

            group_tdah = df_processed[df_processed['TDAH'] == 'Oui'][selected_var].dropna()
            group_no_tdah = df_processed[df_processed['TDAH'] == 'Non'][selected_var].dropna()

            if len(group_tdah) > 0 and len(group_no_tdah) > 0:
                t_stat, p_value = stats.ttest_ind(group_tdah, group_no_tdah)

                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Moyenne TDAH", f"{group_tdah.mean():.2f}")
                with col2:
                    st.metric("Moyenne Non-TDAH", f"{group_no_tdah.mean():.2f}")
                with col3:
                    significance = "Significatif" if p_value < 0.05 else "Non significatif"
                    st.metric("Test t (p-value)", f"{p_value:.4f}", significance)

    with tab3:
        # Matrice de corrélation
        st.subheader("🔗 Analyse des corrélations")

        numeric_df = df_processed.select_dtypes(include=[np.number])

        if len(numeric_df.columns) > 1:
            corr_method = st.selectbox("Méthode de corrélation", ["pearson", "spearman", "kendall"])
            corr_matrix = numeric_df.corr(method=corr_method)

            # Heatmap interactive
            fig = px.imshow(corr_matrix,
                           text_auto=True,
                           aspect="auto",
                           title=f"Matrice de corrélation ({corr_method})",
                           color_continuous_scale='RdBu_r',
                           zmin=-1, zmax=1)
            fig.update_layout(height=600)
            st.plotly_chart(fig, use_container_width=True)

            # Top corrélations
            st.subheader("🔝 Top corrélations")

            # Extraire les corrélations (sans la diagonale)
            mask = np.triu(np.ones_like(corr_matrix), k=1).astype(bool)
            correlations = corr_matrix.where(mask).stack().reset_index()
            correlations.columns = ['Variable 1', 'Variable 2', 'Corrélation']
            correlations = correlations.reindex(correlations['Corrélation'].abs().sort_values(ascending=False).index)

            st.dataframe(correlations.head(10), use_container_width=True)
        else:
            st.warning("Pas assez de variables numériques pour calculer les corrélations")

    with tab4:
        # Feature Engineering
        st.subheader("🎯 Feature Engineering")

        if feature_info:
            st.markdown("**Informations sur le preprocessing :**")

            col1, col2 = st.columns(2)

            with col1:
                st.write(f"Shape originale : {feature_info['original_shape']}")
                st.write(f"Shape après preprocessing : {feature_info['processed_shape']}")

                if 'engineered_features' in feature_info:
                    st.write("**Features créées :**")
                    for feature in feature_info['engineered_features']:
                        st.write(f"- {feature}")

            with col2:
                if 'categorical_mappings' in feature_info:
                    st.write("**Variables encodées :**")
                    for var in feature_info['categorical_mappings'].keys():
                        st.write(f"- {var}")

                if 'age_groups' in feature_info:
                    st.write("**Age groupé en catégories**")

        # Analyse des features importantes
        st.subheader("📊 Importance des features")

        feature_scores = perform_feature_analysis(df_processed)

        if feature_scores is not None:
            # Graphique des scores
            top_features = feature_scores.head(10)

            fig = px.bar(top_features, x='Score', y='Feature', orientation='h',
                        title="Top 10 des features les plus importantes",
                        color='Score', color_continuous_scale='Viridis')
            fig.update_layout(yaxis={'categoryorder': 'total ascending'})
            st.plotly_chart(fig, use_container_width=True)

            # Tableau détaillé
            st.dataframe(feature_scores, use_container_width=True)

def page_machine_learning():
    """Page de machine learning avancé avec optimisation"""
    st.markdown('<h1 class="main-header">🤖 Machine Learning Avancé</h1>', unsafe_allow_html=True)

    try:
        # Chargement et preprocessing des données
        df = load_data()
        if df is None:
            st.error("❌ Impossible de charger les données")
            st.info("💡 Veuillez vérifier votre fichier de données ou télécharger un nouveau fichier.")
            return

        df_processed, _ = advanced_preprocessing(df)
        if df_processed is None:
            st.error("❌ Erreur lors du preprocessing")
            return

        # Vérification de la variable cible
        if 'TDAH' not in df_processed.columns:
            st.error("❌ Variable cible 'TDAH' non trouvée")
            st.info("💡 Assurez-vous que votre fichier contient une colonne nommée 'TDAH', 'diagnosis' ou 'target'.")
            return
     except Exception as e:
        st.error(f"❌ Une erreur s'est produite: {str(e)}")
        st.info("💡 Essayez de recharger la page ou de vérifier vos données.")
            
            
    # Entraînement des modèles
    st.subheader("🚀 Entraînement et optimisation des modèles")
    with st.spinner("Entraînement en cours... Cela peut prendre quelques minutes."):
        results, models, scaler, test_data = train_multiple_models(df_processed)

    if results is None:
        st.error("❌ Impossible d'entraîner les modèles")
        return

    X_test, y_test = test_data

    st.success("✅ Modèles entraînés avec succès!")

    # Onglets pour différentes analyses ML
    tab1, tab2, tab3, tab4 = st.tabs(["📊 Comparaison des modèles", "🎯 Performance détaillée", "📈 Courbes ROC", "⚙️ Hyperparamètres"])

    with tab1:
        # Comparaison des performances
        st.subheader("📊 Comparaison des performances")

        # Métriques principales
        performance_df = pd.DataFrame({
            'Modèle': list(results.keys()),
            'Accuracy': [results[name]['accuracy'] for name in results.keys()],
            'AUC-ROC': [results[name]['auc_score'] for name in results.keys()],
            'CV Score': [results[name]['best_score'] for name in results.keys()]
        }).sort_values('AUC-ROC', ascending=False)

        col1, col2 = st.columns(2)

        with col1:
            # Graphique en barres des performances
            fig = px.bar(performance_df, x='Modèle', y=['Accuracy', 'AUC-ROC', 'CV Score'],
                        title="Comparaison des métriques de performance",
                        barmode='group')
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            # Tableau des performances
            st.dataframe(performance_df.round(4), use_container_width=True)

        # Meilleur modèle
        best_model_name = performance_df.iloc[0]['Modèle']
        best_auc = performance_df.iloc[0]['AUC-ROC']

        st.markdown(f"""
        <div class="success-box">
        <h4>🏆 Meilleur modèle : {best_model_name}</h4>
        <p>AUC-ROC : <strong>{best_auc:.4f}</strong></p>
        <p>Ce modèle montre les meilleures performances pour la classification TDAH.</p>
        </div>
        """, unsafe_allow_html=True)

    with tab2:
        # Performance détaillée
        st.subheader("🎯 Analyse détaillée des performances")

        selected_model = st.selectbox("Sélectionner un modèle pour l'analyse détaillée",
                                     list(results.keys()))

        if selected_model in results:
            model_results = results[selected_model]

            # Métriques détaillées
            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.metric("Accuracy", f"{model_results['accuracy']:.4f}")
            with col2:
                st.metric("AUC-ROC", f"{model_results['auc_score']:.4f}")
            with col3:
                st.metric("CV Score", f"{model_results['best_score']:.4f}")
            with col4:
                st.metric("Échantillons test", len(y_test))

            # Matrice de confusion et rapport de classification
            col1, col2 = st.columns(2)

            with col1:
                # Matrice de confusion
                cm = confusion_matrix(y_test, model_results['y_pred'])

                fig = px.imshow(cm, text_auto=True,
                               labels=dict(x="Prédit", y="Réel"),
                               x=['Non-TDAH', 'TDAH'], y=['Non-TDAH', 'TDAH'],
                               title=f"Matrice de confusion - {selected_model}",
                               color_continuous_scale='Blues')
                st.plotly_chart(fig, use_container_width=True)

            with col2:
                # Distribution des probabilités
                prob_df = pd.DataFrame({
                    'Probabilité': model_results['y_pred_proba'],
                    'Classe réelle': ['TDAH' if x == 1 else 'Non-TDAH' for x in y_test]
                })

                fig = px.histogram(prob_df, x='Probabilité', color='Classe réelle',
                                  title=f"Distribution des probabilités - {selected_model}",
                                  opacity=0.7, nbins=20)
                st.plotly_chart(fig, use_container_width=True)

            # Rapport de classification
            st.subheader("📋 Rapport de classification")

            report = classification_report(y_test, model_results['y_pred'],
                                         target_names=['Non-TDAH', 'TDAH'],
                                         output_dict=True)

            report_df = pd.DataFrame(report).transpose()
            st.dataframe(report_df.round(4), use_container_width=True)

    with tab3:
        # Courbes ROC
        st.subheader("📈 Courbes ROC comparatives")

        fig = go.Figure()

        colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

        for i, (name, model_results) in enumerate(results.items()):
            # Calcul de la courbe ROC
            fpr, tpr, _ = roc_curve(y_test, model_results['y_pred_proba'])
            auc_score = model_results['auc_score']

            fig.add_trace(go.Scatter(
                x=fpr, y=tpr,
                mode='lines',
                name=f'{name} (AUC = {auc_score:.3f})',
                line=dict(color=colors[i % len(colors)], width=2)
            ))

        # Ligne de référence
        fig.add_trace(go.Scatter(
            x=[0, 1], y=[0, 1],
            mode='lines',
            name='Aléatoire (AUC = 0.5)',
            line=dict(color='black', width=1, dash='dash')
        ))

        fig.update_layout(
            title='Courbes ROC - Comparaison des modèles',
            xaxis_title='Taux de Faux Positifs (1 - Spécificité)',
            yaxis_title='Taux de Vrais Positifs (Sensibilité)',
            height=500,
            showlegend=True
        )

        st.plotly_chart(fig, use_container_width=True)

        # Analyse des seuils
        st.subheader("⚖️ Analyse des seuils de classification")

        selected_model_roc = st.selectbox("Sélectionner un modèle pour l'analyse des seuils",
                                         list(results.keys()), key="roc_model")

        if selected_model_roc in results:
            model_results = results[selected_model_roc]
            fpr, tpr, thresholds = roc_curve(y_test, model_results['y_pred_proba'])

            # Calcul des métriques pour différents seuils
            threshold_metrics = []
            for threshold in np.arange(0.1, 1.0, 0.1):
                y_pred_threshold = (model_results['y_pred_proba'] >= threshold).astype(int)
                accuracy = accuracy_score(y_test, y_pred_threshold)

                # Calcul de la sensibilité et spécificité
                cm = confusion_matrix(y_test, y_pred_threshold)
                if cm.shape == (2, 2):
                    tn, fp, fn, tp = cm.ravel()
                    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
                    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
                else:
                    sensitivity = specificity = 0

                threshold_metrics.append({
                    'Seuil': threshold,
                    'Accuracy': accuracy,
                    'Sensibilité': sensitivity,
                    'Spécificité': specificity
                })

            threshold_df = pd.DataFrame(threshold_metrics)

            fig = px.line(threshold_df, x='Seuil', y=['Accuracy', 'Sensibilité', 'Spécificité'],
                         title=f"Métriques par seuil - {selected_model_roc}")
            st.plotly_chart(fig, use_container_width=True)

    with tab4:
        # Hyperparamètres optimaux
        st.subheader("⚙️ Hyperparamètres optimisés")

        for name, model_results in results.items():
            with st.expander(f"📋 {name} - Paramètres optimaux"):
                best_params = model_results['best_params']

                col1, col2 = st.columns(2)

                with col1:
                    st.markdown("**Paramètres optimaux :**")
                    for param, value in best_params.items():
                        st.write(f"- **{param}**: {value}")

                with col2:
                    st.markdown("**Métriques :**")
                    st.write(f"- **CV Score**: {model_results['best_score']:.4f}")
                    st.write(f"- **Test Accuracy**: {model_results['accuracy']:.4f}")
                    st.write(f"- **Test AUC-ROC**: {model_results['auc_score']:.4f}")

        # Importance des features pour Random Forest
        if 'Random Forest' in models and hasattr(models['Random Forest'], 'feature_importances_'):
            st.subheader("🎯 Importance des variables (Random Forest)")

            # Récupération des features numériques
            numeric_features = df_processed.select_dtypes(include=[np.number]).drop(columns=['TDAH'], errors='ignore').columns

            if len(numeric_features) == len(models['Random Forest'].feature_importances_):
                importance_df = pd.DataFrame({
                    'Feature': numeric_features,
                    'Importance': models['Random Forest'].feature_importances_
                }).sort_values('Importance', ascending=True)

                fig = px.bar(importance_df.tail(10), x='Importance', y='Feature',
                            orientation='h',
                            title="Top 10 des variables les plus importantes",
                            color='Importance', color_continuous_scale='Viridis')
                st.plotly_chart(fig, use_container_width=True)

    # Sauvegarde du modèle
    st.subheader("💾 Sauvegarde du meilleur modèle")

    if st.button("Sauvegarder le meilleur modèle", type="primary"):
        try:
            best_model_name = max(results.keys(), key=lambda x: results[x]['auc_score'])
            best_model = models[best_model_name]

            model_data = {
                'model': best_model,
                'scaler': scaler,
                'model_name': best_model_name,
                'performance': results[best_model_name],
                'feature_names': df_processed.select_dtypes(include=[np.number]).drop(columns=['TDAH'], errors='ignore').columns.tolist(),
                'timestamp': datetime.now().isoformat()
            }

            joblib.dump(model_data, 'best_tdah_model.pkl')

            st.success(f"✅ Modèle {best_model_name} sauvegardé avec succès!")
            st.balloons()

        except Exception as e:
            st.error(f"❌ Erreur lors de la sauvegarde : {str(e)}")

def page_prediction():
    """Page de prédiction avec IA"""
    st.markdown('<h1 class="main-header">🎯 Prédiction TDAH par IA</h1>', unsafe_allow_html=True)

    st.markdown("""
    <div class="info-box">
    <h4>🤖 Prédiction par Intelligence Artificielle</h4>
    <p>Cette section utilise des modèles de machine learning entraînés pour estimer
    la probabilité de TDAH basée sur vos réponses. Les résultats sont à des fins
    d'information uniquement et ne remplacent pas un diagnostic médical.</p>
    </div>
    """, unsafe_allow_html=True)

    # Chargement du modèle sauvegardé
    try:
        model_data = joblib.load('best_tdah_model.pkl')
        st.success(f"✅ Modèle {model_data['model_name']} chargé")

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Modèle", model_data['model_name'])
        with col2:
            st.metric("Accuracy", f"{model_data['performance']['accuracy']:.2%}")
        with col3:
            st.metric("AUC-ROC", f"{model_data['performance']['auc_score']:.3f}")

    except FileNotFoundError:
        st.warning("⚠️ Aucun modèle sauvegardé trouvé. Entraînez d'abord un modèle dans la section Machine Learning.")

        # Entraînement temporaire pour la démonstration
        df = load_data()
        if df is not None:
            df_processed, _ = advanced_preprocessing(df)
            if df_processed is not None and 'TDAH' in df_processed.columns:
                with st.spinner("Entraînement d'un modèle temporaire..."):
                    results, models, scaler, _ = train_multiple_models(df_processed)
                    if results is not None:
                        best_model_name = max(results.keys(), key=lambda x: results[x]['auc_score'])
                        model_data = {
                            'model': models[best_model_name],
                            'scaler': scaler,
                            'model_name': best_model_name,
                            'performance': results[best_model_name],
                            'feature_names': df_processed.select_dtypes(include=[np.number]).drop(columns=['TDAH'], errors='ignore').columns.tolist()
                        }
                        st.success("✅ Modèle temporaire créé")
                    else:
                        st.error("❌ Impossible de créer un modèle")
                        return
            else:
                st.error("❌ Données non disponibles pour l'entraînement")
                return
        else:
            st.error("❌ Impossible de charger les données")
            return

    # Interface de prédiction
    st.subheader("📝 Saisie des informations pour la prédiction")

    with st.form("prediction_form"):
        # Informations de base
        st.markdown("**Informations démographiques**")
        col1, col2 = st.columns(2)

        with col1:
            age = st.number_input("Âge", min_value=6, max_value=80, value=25)
            genre = st.selectbox("Genre", ["Féminin", "Masculin"])

        with col2:
            niveau_etudes = st.selectbox("Niveau d'études",
                                       ["Primaire", "Collège", "Lycée", "Université", "Post-universitaire"])
            situation_pro = st.selectbox("Situation professionnelle",
                                       ["Étudiant", "Employé", "Indépendant", "Sans emploi", "Retraité"])

        # Scores comportementaux
        st.markdown("**Scores comportementaux (1-10, 10 = symptômes très présents)**")
        col1, col2, col3 = st.columns(3)

        with col1:
            inattention = st.slider("Score d'inattention", 1.0, 10.0, 5.0, 0.5,
                                  help="Difficultés de concentration, erreurs d'inattention, oublis")

        with col2:
            hyperactivite = st.slider("Score d'hyperactivité", 1.0, 10.0, 5.0, 0.5,
                                    help="Agitation motrice, difficulté à rester assis")

        with col3:
            impulsivite = st.slider("Score d'impulsivité", 1.0, 10.0, 5.0, 0.5,
                                  help="Interruptions, difficultés à attendre, décisions impulsives")

        # Facteurs contextuels
        st.markdown("**Facteurs contextuels (1-10)**")
        col1, col2 = st.columns(2)

        with col1:
            sommeil = st.slider("Problèmes de sommeil", 1.0, 10.0, 5.0, 0.5)
            anxiete = st.slider("Niveau d'anxiété", 1.0, 10.0, 5.0, 0.5)

        with col2:
            stress = st.slider("Niveau de stress", 1.0, 10.0, 5.0, 0.5)
            concentration = st.slider("Difficultés de concentration", 1.0, 10.0, 5.0, 0.5)

        # Antécédents
        st.markdown("**Antécédents**")
        col1, col2 = st.columns(2)

        with col1:
            antecedents_familiaux = st.selectbox("Antécédents familiaux TDAH", ["Non", "Oui", "Incertain"])
            troubles_apprentissage = st.selectbox("Troubles d'apprentissage", ["Non", "Oui", "Incertain"])

        with col2:
            medicaments = st.selectbox("Prise de médicaments psychotropes", ["Non", "Oui"])
            suivi_psy = st.selectbox("Suivi psychologique actuel", ["Non", "Oui"])

        predict_button = st.form_submit_button("🔮 Effectuer la prédiction", type="primary")

    if predict_button:
        try:
            # Préparation des données d'entrée
            # Encodage des variables catégorielles
            genre_encoded = 1 if genre == "Masculin" else 0
            antecedents_encoded = 1 if antecedents_familiaux == "Oui" else 0

            # Création du vecteur de features (adapté aux features du modèle)
            input_features = [
                age, genre_encoded, inattention, hyperactivite, impulsivite,
                sommeil, anxiete, stress, concentration, antecedents_encoded
            ]

            # Ajustement selon le nombre de features attendues
            expected_features = len(model_data.get('feature_names', input_features))

            # Compléter ou tronquer selon les besoins
            while len(input_features) < expected_features:
                input_features.append(5.0)  # Valeur par défaut
            input_features = input_features[:expected_features]

            input_array = np.array(input_features).reshape(1, -1)

            # Normalisation si nécessaire
            if 'scaler' in model_data and model_data['scaler'] is not None:
                input_scaled = model_data['scaler'].transform(input_array)
            else:
                input_scaled = input_array

            # Prédiction
            model = model_data['model']
            prediction = model.predict(input_scaled)[0]
            prediction_proba = model.predict_proba(input_scaled)[0]

            # Affichage des résultats
            st.success("🎯 Prédiction terminée!")

            # Métriques principales
            col1, col2, col3 = st.columns(3)

            risk_percentage = prediction_proba[1] * 100

            with col1:
                st.metric(
                    "Probabilité TDAH",
                    f"{risk_percentage:.1f}%",
                    delta=f"{'Élevé' if risk_percentage > 60 else 'Modéré' if risk_percentage > 40 else 'Faible'}"
                )

            with col2:
                prediction_text = "TDAH Probable" if prediction == 1 else "TDAH Peu Probable"
                confidence = max(prediction_proba) * 100
                st.metric("Prédiction", prediction_text, f"Confiance: {confidence:.1f}%")

            with col3:
                st.metric("Modèle utilisé", model_data['model_name'],
                         f"AUC: {model_data['performance']['auc_score']:.3f}")

            # Visualisation du risque
            st.subheader("📊 Visualisation du risque")

            # Gauge chart
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta",
                value=risk_percentage,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': "Probabilité de TDAH (%)"},
                delta={'reference': 50},
                gauge={
                    'axis': {'range': [None, 100]},
                    'bar': {'color': "#1976d2"},
                    'steps': [
                        {'range': [0, 30], 'color': "#c8e6c8"},
                        {'range': [30, 60], 'color': "#ffe0b2"},
                        {'range': [60, 80], 'color': "#ffcdd2"},
                        {'range': [80, 100], 'color': "#ffcdd2"}
                    ],
                    'threshold': {
                        'line': {'color': "red", 'width': 4},
                        'thickness': 0.75,
                        'value': 70
                    }
                }
            ))

            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

            # Analyse des facteurs de risque
            st.subheader("🔍 Analyse des facteurs")

            # Graphique radar des scores comportementaux
            categories = ['Inattention', 'Hyperactivité', 'Impulsivité', 'Sommeil', 'Anxiété', 'Stress']
            values = [inattention, hyperactivite, impulsivite, sommeil, anxiete, stress]

            fig = go.Figure()

            fig.add_trace(go.Scatterpolar(
                r=values,
                theta=categories,
                fill='toself',
                name='Vos scores',
                line_color='#1976d2'
            ))

            fig.add_trace(go.Scatterpolar(
                r=[5] * len(categories),
                theta=categories,
                fill='toself',
                name='Moyenne population',
                line_color='#ff7f0e',
                opacity=0.3
            ))

            fig.update_layout(
                polar=dict(
                    radialaxis=dict(
                        visible=True,
                        range=[0, 10]
                    )),
                showlegend=True,
                title="Profil comportemental",
                height=500
            )

            st.plotly_chart(fig, use_container_width=True)

            # Recommandations personnalisées
            st.subheader("💡 Recommandations personnalisées")

            if risk_percentage > 70:
                st.markdown("""
                <div class="warning-box">
                <h4>🔴 Risque élevé de TDAH détecté</h4>
                <p><strong>Recommandations urgentes :</strong></p>
                <ul>
                <li>📞 Consultez rapidement un professionnel de santé spécialisé (psychiatre, neurologue)</li>
                <li>📋 Demandez une évaluation diagnostique complète</li>
                <li>📝 Préparez un historique détaillé de vos symptômes</li>
                <li>👥 Informez votre entourage proche de vos difficultés</li>
                </ul>
                </div>
                """, unsafe_allow_html=True)

            elif risk_percentage > 40:
                st.markdown("""
                <div class="warning-box">
                <h4>🟡 Risque modéré de TDAH</h4>
                <p><strong>Recommandations :</strong></p>
                <ul>
                <li>🩺 Consultez votre médecin traitant pour discuter de vos symptômes</li>
                <li>📊 Surveillez l'évolution de vos difficultés</li>
                <li>📚 Documentez vos symptômes dans un journal</li>
                <li>🧘 Explorez des stratégies de gestion du stress</li>
                </ul>
                </div>
                """, unsafe_allow_html=True)

            else:
                st.markdown("""
                <div class="success-box">
                <h4>🟢 Risque faible de TDAH</h4>
                <p><strong>Informations :</strong></p>
                <ul>
                <li>✅ Vos réponses ne suggèrent pas la présence de TDAH</li>
                <li>👀 Continuez à surveiller vos symptômes si vous avez des préoccupations</li>
                <li>💪 Maintenez de bonnes habitudes de vie</li>
                <li>🩺 Consultez si les symptômes s'aggravent ou persistent</li>
                </ul>
                </div>
                """, unsafe_allow_html=True)

            # Facteurs de risque identifiés
            risk_factors = []
            if inattention >= 7:
                risk_factors.append("Score d'inattention élevé")
            if hyperactivite >= 7:
                risk_factors.append("Score d'hyperactivité élevé")
            if impulsivite >= 7:
                risk_factors.append("Score d'impulsivité élevé")
            if antecedents_familiaux == "Oui":
                risk_factors.append("Antécédents familiaux présents")
            if sommeil >= 7:
                risk_factors.append("Problèmes de sommeil importants")

            if risk_factors:
                st.markdown("**⚠️ Facteurs de risque identifiés :**")
                for factor in risk_factors:
                    st.write(f"• {factor}")

        except Exception as e:
            st.error(f"❌ Erreur lors de la prédiction : {str(e)}")
            st.info("💡 Vérifiez que le modèle est correctement entraîné dans la section Machine Learning.")

def page_test_asrs():
    """Page de test ASRS-v1.1 complet"""
    st.markdown('<h1 class="main-header">📝 Test ASRS-v1.1 Officiel</h1>', unsafe_allow_html=True)

    st.markdown("""
    <div class="info-box">
    <h4>🔍 À propos du test ASRS-v1.1</h4>
    <p>L'Adult ADHD Self-Report Scale (ASRS-v1.1) est l'outil de dépistage de référence
    développé par l'Organisation Mondiale de la Santé en collaboration avec Harvard Medical School.
    Il comprend 18 questions basées sur les critères DSM-5 pour le TDAH chez l'adulte.</p>
    </div>
    """, unsafe_allow_html=True)

    # Questions ASRS-v1.1 complètes (version française officielle)
    questions_part_a = {
        1: "À quelle fréquence avez-vous du mal à terminer les détails finaux d'un projet, une fois que les parties difficiles ont été faites ?",
        2: "À quelle fréquence avez-vous des difficultés à mettre les choses en ordre quand vous devez faire une tâche qui nécessite de l'organisation ?",
        3: "À quelle fréquence avez-vous des problèmes pour vous rappeler des rendez-vous ou des obligations ?",
        4: "Quand vous avez une tâche qui demande beaucoup de réflexion, à quelle fréquence évitez-vous ou retardez-vous de commencer ?",
        5: "À quelle fréquence bougez-vous ou vous agitez-vous avec vos mains ou vos pieds quand vous devez rester assis longtemps ?",
        6: "À quelle fréquence vous sentez-vous trop actif et obligé de faire des choses, comme si vous étiez mené par un moteur ?"
    }

    questions_part_b = {
        7: "À quelle fréquence faites-vous des erreurs d'inattention quand vous devez travailler sur un projet ennuyeux ou difficile ?",
        8: "À quelle fréquence avez-vous des difficultés à maintenir votre attention quand vous faites un travail ennuyeux ou répétitif ?",
        9: "À quelle fréquence avez-vous des difficultés à vous concentrer sur ce que les gens vous disent, même quand ils vous parlent directement ?",
        10: "À quelle fréquence égarez-vous ou avez des difficultés à trouver des choses à la maison ou au travail ?",
        11: "À quelle fréquence êtes-vous distrait par l'activité ou le bruit autour de vous ?",
        12: "À quelle fréquence quittez-vous votre siège dans des réunions ou d'autres situations où vous êtes supposé rester assis ?",
        13: "À quelle fréquence vous sentez-vous agité ou nerveux ?",
        14: "À quelle fréquence avez-vous des difficultés à vous détendre quand vous avez du temps libre ?",
        15: "À quelle fréquence vous trouvez-vous en train de trop parler dans des situations sociales ?",
        16: "Quand vous êtes en conversation, à quelle fréquence vous surprenez-vous à finir les phrases des personnes à qui vous parlez, avant qu'elles puissent les finir elles-mêmes ?",
        17: "À quelle fréquence avez-vous des difficultés à attendre votre tour dans des situations où chacun doit attendre son tour ?",
        18: "À quelle fréquence interrompez-vous les autres quand ils sont occupés ?"
    }

    # Options de réponse
    options = ["Jamais", "Rarement", "Parfois", "Souvent", "Très souvent"]

    # Initialisation des réponses dans le session state
    if 'asrs_responses' not in st.session_state:
        st.session_state.asrs_responses = {}

    # Formulaire de questionnaire
    with st.form("asrs_questionnaire"):
        # Part A - Questions de dépistage
        st.markdown('<h3 style="color: #1976d2;">📋 Partie A - Questions de dépistage principales</h3>', unsafe_allow_html=True)
        st.markdown("*Ces 6 questions sont les plus prédictives du TDAH selon les recherches de l'OMS*")

        for q_num, text in questions_part_a.items():
            st.session_state.asrs_responses[q_num] = st.radio(
                f"**Question {q_num}:** {text}",
                options=options,
                index=0,  # "Jamais" par défaut
                key=f"q{q_num}",
                help="Choisissez la fréquence qui correspond le mieux à votre expérience"
            )

        st.markdown("---")

        # Part B - Questions complémentaires
        st.markdown('<h3 style="color: #1976d2;">📋 Partie B - Questions complémentaires</h3>', unsafe_allow_html=True)
        st.markdown("*Ces questions permettent une évaluation plus complète des symptômes*")

        for q_num, text in questions_part_b.items():
            st.session_state.asrs_responses[q_num] = st.radio(
                f"**Question {q_num}:** {text}",
                options=options,
                index=0,  # "Jamais" par défaut
                key=f"q{q_num}",
                help="Choisissez la fréquence qui correspond le mieux à votre expérience"
            )

        submitted = st.form_submit_button("🔍 Calculer mon score ASRS", type="primary")

    if submitted:
        # Vérification que toutes les questions ont une réponse
        if len(st.session_state.asrs_responses) < 18:
            st.error("❌ Veuillez répondre à toutes les questions avant de calculer le score.")
            return

        # Calcul des scores selon les critères officiels ASRS
        score_mapping = {"Jamais": 0, "Rarement": 1, "Parfois": 2, "Souvent": 3, "Très souvent": 4}

        # Scores par partie
        part_a_scores = [score_mapping[st.session_state.asrs_responses[i]] for i in range(1, 7)]
        part_a_total = sum(part_a_scores)

        part_b_scores = [score_mapping[st.session_state.asrs_responses[i]] for i in range(7, 19)]
        part_b_total = sum(part_b_scores)

        total_score = part_a_total + part_b_total

        # Critères de dépistage positif pour Part A (selon recherches OMS)
        # Seuils spécifiques par question pour Part A
        part_a_thresholds = [2, 2, 2, 2, 2, 2]  # Seuils cliniques validés
        part_a_positive = sum([1 for i, score in enumerate(part_a_scores) if score >= part_a_thresholds[i]])

        # Analyse par domaine (Inattention vs Hyperactivité/Impulsivité)
        inattention_questions = [1, 2, 3, 4, 7, 8, 9, 10, 11]
        hyperactivity_questions = [5, 6, 12, 13, 14, 15, 16, 17, 18]

        inattention_score = sum([score_mapping[st.session_state.asrs_responses[i]] for i in inattention_questions])
        hyperactivity_score = sum([score_mapping[st.session_state.asrs_responses[i]] for i in hyperactivity_questions])

        # Affichage des résultats
        st.success("✅ Questionnaire ASRS-v1.1 complété!")

        # Métriques principales
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("Score Partie A", f"{part_a_total}/24", f"{part_a_positive}/6 critères positifs")

        with col2:
            st.metric("Score Partie B", f"{part_b_total}/48")

        with col3:
            st.metric("Score Total", f"{total_score}/72", f"{(total_score/72)*100:.1f}%")

        with col4:
            risk_level = "Élevé" if part_a_positive >= 4 else "Modéré" if part_a_positive >= 2 else "Faible"
            st.metric("Niveau de risque", risk_level)

        # Interprétation clinique officielle
        st.subheader("🎯 Interprétation clinique")

        if part_a_positive >= 4:
            st.markdown("""
            <div class="warning-box">
            <h4>🔴 Dépistage POSITIF - Symptômes hautement compatibles avec un TDAH</h4>
            <p><strong>Signification clinique :</strong> Vos réponses à la Partie A indiquent une forte probabilité
            de présence de symptômes TDAH selon les critères de l'OMS.</p>

            <p><strong>Recommandations urgentes :</strong></p>
            <ul>
            <li>📞 <strong>Consultez rapidement un professionnel de santé spécialisé</strong> (psychiatre, neurologue, médecin formé au TDAH)</li>
            <li>📋 Demandez une évaluation diagnostique complète incluant entretien clinique et tests neuropsychologiques</li>
            <li>📝 Préparez un historique détaillé de vos symptômes depuis l'enfance</li>
            <li>👥 Contactez des associations de patients TDAH pour support et information</li>
            </ul>

            <p><strong>⚠️ Important :</strong> Ce test de dépistage ne constitue pas un diagnostic.
            Seul un professionnel de santé qualifié peut poser un diagnostic de TDAH.</p>
            </div>
            """, unsafe_allow_html=True)

        elif part_a_positive >= 2:
            st.markdown("""
            <div class="warning-box">
            <h4>🟡 Dépistage MODÉRÉ - Certains symptômes TDAH présents</h4>
            <p><strong>Signification clinique :</strong> Vos réponses suggèrent la présence de certains symptômes
            compatibles avec le TDAH, nécessitant une attention particulière.</p>

            <p><strong>Recommandations :</strong></p>
            <ul>
            <li>🩺 Consultez votre médecin traitant pour discuter de vos préoccupations</li>
            <li>📊 Surveillez l'évolution de vos symptômes sur plusieurs semaines</li>
            <li>📚 Tenez un journal de vos difficultés quotidiennes</li>
            <li>🧘 Explorez des stratégies de gestion des symptômes (organisation, mindfulness)</li>
            <li>👥 Considérez un suivi spécialisé si les symptômes persistent ou s'aggravent</li>
            </ul>
            </div>
            """, unsafe_allow_html=True)

        else:
            st.markdown("""
            <div class="success-box">
            <h4>🟢 Dépistage NÉGATIF - Peu de symptômes TDAH détectés</h4>
            <p><strong>Signification clinique :</strong> Vos réponses ne suggèrent pas la présence
            de symptômes TDAH significatifs selon les critères de dépistage de l'OMS.</p>

            <p><strong>Informations importantes :</strong></p>
            <ul>
            <li>✅ Vos difficultés actuelles peuvent avoir d'autres causes (stress, fatigue, autres troubles)</li>
            <li>👀 Continuez à surveiller vos symptômes - le TDAH peut se manifester différemment selon les périodes</li>
            <li>💪 Maintenez de bonnes habitudes de vie (sommeil, exercice, organisation)</li>
            <li>🩺 N'hésitez pas à consulter si vous avez d'autres préoccupations de santé mentale</li>
            </ul>
            </div>
            """, unsafe_allow_html=True)

        # Visualisations détaillées
        st.subheader("📊 Analyse détaillée de vos réponses")

        # Graphique des scores par domaine
        col1, col2 = st.columns(2)

        with col1:
            domains_df = pd.DataFrame({
                'Domaine': ['Inattention', 'Hyperactivité/Impulsivité'],
                'Score': [inattention_score, hyperactivity_score],
                'Score_Max': [36, 36],  # 9 questions * 4 points max chacune
                'Pourcentage': [
                    (inattention_score / 36) * 100,
                    (hyperactivity_score / 36) * 100
                ]
            })

            fig = px.bar(domains_df, x='Domaine', y='Pourcentage',
                        title="Répartition des symptômes par domaine (%)",
                        color='Pourcentage',
                        color_continuous_scale='RdYlBu_r',
                        text='Pourcentage')
            fig.update_traces(texttemplate='%{text:.1f}%', textposition='outside')
            fig.update_layout(height=400, yaxis_range=[0, 100])
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            # Répartition des réponses par fréquence
            response_counts = pd.Series(list(st.session_state.asrs_responses.values())).value_counts()

            fig = px.pie(values=response_counts.values, names=response_counts.index,
                        title="Répartition de vos réponses par fréquence",
                        color_discrete_sequence=px.colors.qualitative.Set3)
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)

        # Graphique radar détaillé
        st.subheader("🎯 Profil détaillé des symptômes")

        # Regroupement des questions par thème
        themes = {
            'Organisation': [1, 2, 10],
            'Attention soutenue': [7, 8, 9, 11],
            'Mémoire': [3],
            'Procrastination': [4],
            'Hyperactivité motrice': [5, 12],
            'Hyperactivité mentale': [6, 13, 14],
            'Impulsivité verbale': [15, 16],
            'Impulsivité comportementale': [17, 18]
        }

        theme_scores = {}
        for theme, questions in themes.items():
            scores = [score_mapping[st.session_state.asrs_responses[q]] for q in questions]
            theme_scores[theme] = np.mean(scores)

        fig = go.Figure()

        fig.add_trace(go.Scatterpolar(
            r=list(theme_scores.values()),
            theta=list(theme_scores.keys()),
            fill='toself',
            name='Vos scores',
            line_color='#1976d2'
        ))

        fig.add_trace(go.Scatterpolar(
            r=[2] * len(theme_scores),  # Seuil moyen
            theta=list(theme_scores.keys()),
            fill='toself',
            name='Seuil de préoccupation',
            line_color='#ff7f0e',
            opacity=0.3
        ))

        fig.update_layout(
            polar=dict(
                radialaxis=dict(
                    visible=True,
                    range=[0, 4],
                    tickvals=[0, 1, 2, 3, 4],
                    ticktext=['Jamais', 'Rarement', 'Parfois', 'Souvent', 'Très souvent']
                )),
            showlegend=True,
            title="Profil détaillé par domaine de symptômes",
            height=600
        )

        st.plotly_chart(fig, use_container_width=True)

        # Recommandations spécifiques par domaine
        st.subheader("💡 Recommandations spécifiques")

        high_score_domains = [domain for domain, score in theme_scores.items() if score >= 2.5]

        if high_score_domains:
            st.markdown("**Domaines nécessitant une attention particulière :**")

            recommendations = {
                'Organisation': "📋 Utilisez des outils d'organisation (agenda, listes, applications), créez des routines structurées",
                'Attention soutenue': "🎯 Pratiquez des exercices de mindfulness, éliminez les distractions, prenez des pauses régulières",
                'Mémoire': "📝 Utilisez des rappels, notez tout, créez des associations visuelles",
                'Procrastination': "⏰ Découpez les tâches en étapes, utilisez la technique Pomodoro, fixez des échéances",
                'Hyperactivité motrice': "🏃‍♂️ Intégrez de l'exercice physique régulier, utilisez des objets anti-stress",
                'Hyperactivité mentale': "🧘 Pratiquez la méditation, apprenez des techniques de relaxation",
                'Impulsivité verbale': "🤐 Pratiquez l'écoute active, comptez jusqu'à 3 avant de parler",
                'Impulsivité comportementale': "⏸️ Développez des stratégies de pause, réfléchissez avant d'agir"
            }

            for domain in high_score_domains:
                if domain in recommendations:
                    st.write(f"• **{domain}** : {recommendations[domain]}")

        # Export des résultats
        st.subheader("💾 Sauvegarde de vos résultats")

        if st.button("📄 Générer un rapport PDF", type="secondary"):
            # Création d'un rapport simple en text
            report_text = f"""
RAPPORT DE DÉPISTAGE TDAH - ASRS-v1.1
=====================================

Date: {datetime.now().strftime('%d/%m/%Y %H:%M')}

SCORES:
- Partie A: {part_a_total}/24 ({part_a_positive}/6 critères positifs)
- Partie B: {part_b_total}/48
- Score Total: {total_score}/72 ({(total_score/72)*100:.1f}%)

INTERPRÉTATION:
- Niveau de risque: {risk_level}
- Domaine Inattention: {inattention_score}/36 ({(inattention_score/36)*100:.1f}%)
- Domaine Hyperactivité/Impulsivité: {hyperactivity_score}/36 ({(hyperactivity_score/36)*100:.1f}%)

RECOMMANDATION:
{"Consultation spécialisée recommandée" if part_a_positive >= 4 else "Surveillance et consultation si symptômes persistent" if part_a_positive >= 2 else "Pas d'indication de TDAH selon ce dépistage"}

IMPORTANT: Ce dépistage ne remplace pas un diagnostic médical professionnel.
            """

            st.download_button(
                label="Télécharger le rapport",
                data=report_text,
                file_name=f"rapport_asrs_{datetime.now().strftime('%Y%m%d_%H%M')}.txt",
                mime="text/plain"
            )

# =================== NAVIGATION PRINCIPALE ===================

def main():
    """Fonction principale avec navigation"""

    # Sidebar avec style amélioré
    st.sidebar.markdown("""
    <div style="text-align: center; padding: 1.5rem; background: linear-gradient(145deg, #e3f2fd, #bbdefb); border-radius: 10px; margin-bottom: 1rem;">
        <h1 style="color: #1976d2; margin-bottom: 0.5rem;">🧠 TDAH</h1>
        <p style="color: #1565c0; font-size: 1rem; margin-bottom: 0;">Dépistage & IA Avancée</p>
    </div>
    """, unsafe_allow_html=True)

    # Menu de navigation
    pages = {
        "🏠 Accueil": page_accueil,
        "📊 Exploration des Données": page_exploration,
        "🤖 Machine Learning": page_machine_learning,
        "🎯 Prédiction IA": page_prediction,
        "📝 Test ASRS-v1.1": page_test_asrs
    }

    selected_page = st.sidebar.selectbox(
        "Navigation",
        list(pages.keys()),
        help="Sélectionnez la section que vous souhaitez explorer"
    )

    # Informations sur les données dans la sidebar
    st.sidebar.markdown("---")
    st.sidebar.markdown("**📊 Informations système**")

    # Test de chargement des données
    df = load_data()
    if df is not None and not df.empty:
        st.sidebar.success("✅ Données chargées")
        st.sidebar.info(f"📈 {len(df)} échantillons")
        st.sidebar.info(f"📋 {len(df.columns)} variables")

        if 'TDAH' in df.columns:
            tdah_count = (df['TDAH'] == 'Oui').sum()
            st.sidebar.info(f"🎯 {tdah_count} cas TDAH")
    else:
        st.sidebar.error("❌ Données non disponibles")

    # Informations sur les modèles
    try:
        model_data = joblib.load('best_tdah_model.pkl')
        st.sidebar.success("🤖 Modèle IA disponible")
        st.sidebar.info(f"🏆 {model_data['model_name']}")
    except FileNotFoundError:
        st.sidebar.warning("⚠️ Modèle IA non entraîné")

    # Footer de la sidebar
    st.sidebar.markdown("---")
    st.sidebar.markdown("""
    <div style="text-align: center; font-size: 0.8rem; color: #666;">
    <p>⚠️ Outil de recherche uniquement<br>
    Ne remplace pas un diagnostic médical</p>
    </div>
    """, unsafe_allow_html=True)

    # Affichage de la page sélectionnée
    try:
        pages[selected_page]()
    except Exception as e:
        st.error(f"❌ Erreur lors du chargement de la page : {str(e)}")
        st.info("💡 Essayez de recharger la page ou sélectionnez une autre section.")

# =================== LANCEMENT DE L'APPLICATION ===================

if __name__ == "__main__":
    main()
